'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Shell from '../../../components/Shell'
import { api, disclaimer, getSession } from '../../../lib/client'

const tabs = ['Overview', 'Documents', 'Ask CaseWise', 'AI Analysis', 'Timeline', 'Claims', 'Evidence', 'Hearings', 'Tasks', 'Payments', 'Notes']
const map = { Timeline: 'timeline_events', Claims: 'claims', Evidence: 'evidence', Hearings: 'hearings', Tasks: 'tasks', Payments: 'payments', Notes: 'case_notes' }
const fields = { Timeline: [['event_date', 'date'], ['description', 'text']], Claims: [['statement', 'text']], Evidence: [['name', 'text'], ['type', 'text'], ['description', 'text']], Hearings: [['starts_at', 'datetime-local'], ['court', 'text'], ['purpose', 'text']], Tasks: [['title', 'text'], ['due_at', 'datetime-local']], Payments: [['total_fee', 'number'], ['amount_paid', 'number'], ['due_date', 'date']], Notes: [['body', 'text']] }
export default function CasePage() {
  const { id } = useParams(), router = useRouter()
  const [item, setItem] = useState(null), [tab, setTab] = useState('Overview')
  const [docs, setDocs] = useState([]), [records, setRecords] = useState([]), [question, setQuestion] = useState(''), [answer, setAnswer] = useState(null)
  const [draft, setDraft] = useState({}), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [inviteStatus, setInviteStatus] = useState('')
  const [analyses, setAnalyses] = useState([])
  useEffect(() => { if (!getSession()) { router.push('/'); return } api(`/cases/${id}`).then(setItem).catch(e => setError(e.message)) }, [id, router])
  useEffect(() => { if (!item) return; setError(''); if (tab === 'Documents' || tab === 'Overview') api(`/cases/${id}/documents`).then(setDocs).catch(e => setError(e.message)); if (tab === 'AI Analysis') api(`/cases/${id}/ai_analyses`).then(setAnalyses).catch(e => setError(e.message)); if (map[tab]) api(`/cases/${id}/${map[tab]}`).then(setRecords).catch(e => setError(e.message)) }, [id, item, tab])
  async function upload(e) {
    const files = Array.from(e.target.files || []); setBusy(true); setError('')
    try { for (const file of files) { const body = new FormData(); body.append('file', file); await api(`/cases/${id}/documents`, { method: 'POST', body }) } setDocs(await api(`/cases/${id}/documents`)) } catch (e) { setError(e.message) } finally { setBusy(false) }
  }
  async function ask(e) { e.preventDefault(); setBusy(true); setError(''); setAnswer(null); try { setAnswer(await api(`/cases/${id}/ask`, { method: 'POST', body: JSON.stringify({ question }) })) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function add(e) { e.preventDefault(); setBusy(true); setError(''); try { await api(`/cases/${id}/${map[tab]}`, { method: 'POST', body: JSON.stringify({ data: draft }) }); setRecords(await api(`/cases/${id}/${map[tab]}`)); setDraft({}) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function openDocument(docId) { try { const blob = await api(`/cases/${id}/documents/${docId}/file`); const url = URL.createObjectURL(blob); window.open(url, '_blank'); setTimeout(() => URL.revokeObjectURL(url), 60000) } catch (e) { setError(e.message) } }
  async function invite() { setError(''); try { await api(`/cases/${id}/members`, { method: 'POST', body: JSON.stringify({ email: item.client.email }) }); setInviteStatus('Client access granted') } catch (e) { setError(e.message) } }
  async function analyze() { setBusy(true); setError(''); try { await api(`/cases/${id}/analyze`, { method: 'POST' }); setAnalyses(await api(`/cases/${id}/ai_analyses`)) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  if (!item) return <div className="center-card">{error || 'Loading case…'}</div>
  const lawyer = item.member_role === 'LAWYER'
  return <Shell title={item.title} subtitle={`${item.case_number || 'No case number'} · ${item.court || 'Court not set'}`} role={item.member_role}><div className="case-heading"><Link href="/" className="back">← All cases</Link><span className={`badge ${item.status.toLowerCase()}`}>{item.status}</span></div><div className="tabs">{tabs.filter(t => lawyer || !['Ask CaseWise', 'AI Analysis', 'Notes'].includes(t)).map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t}</button>)}</div>{error && <div className="error">{error}</div>}
    {tab === 'Overview' && <div className="overview-grid"><section className="panel"><div className="eyebrow">CASE SUMMARY</div><h2>{item.main_issue || 'Main issue not set'}</h2><p className="body-copy">{item.description || 'Add case details to build the record.'}</p><dl><div><dt>Case type</dt><dd>{item.case_type || '—'}</dd></div><div><dt>Priority</dt><dd>{item.priority}</dd></div><div><dt>Filing date</dt><dd>{item.filing_date || '—'}</dd></div><div><dt>Client</dt><dd>{item.client?.name || '—'}</dd></div></dl>{lawyer && item.client?.email && <div className="invite"><p className="muted">Give {item.client.email} access after they create a client account.</p><button className="primary" onClick={invite}>Grant client access</button>{inviteStatus && <p>{inviteStatus}</p>}</div>}</section><section className="panel"><div className="eyebrow">DOCUMENTS</div><h2>Processing status</h2>{docs.length ? docs.map(d => <div className="file-line" key={d.id}>{d.file_name}<span className={`badge ${d.processing_status.toLowerCase()}`}>{d.processing_status}</span></div>) : <p className="muted">No documents uploaded.</p>}<button className="link-button" onClick={() => setTab('Documents')}>View documents →</button></section></div>}
    {tab === 'Documents' && <section className="panel"><div className="panel-head"><div><div className="eyebrow">CASE SOURCES</div><h2>Documents</h2></div>{lawyer && <label className="primary upload">{busy ? 'Uploading…' : '+ Upload documents'}<input type="file" accept=".pdf,.docx,.txt" multiple onChange={upload} disabled={busy} /></label>}</div>{docs.length ? docs.map(d => <div className="file-line" key={d.id}><button className="link-button" onClick={() => openDocument(d.id)}>{d.file_name}</button><span className={`badge ${d.processing_status.toLowerCase()}`}>{d.processing_status}</span>{d.error_message && <small className="error-text">{d.error_message}</small>}</div>) : <div className="empty">No documents yet. Upload PDF, DOCX or TXT files.</div>}<p className="muted">Refresh this tab to see updated processing states.</p></section>}
    {tab === 'Ask CaseWise' && <section className="panel"><div className="eyebrow">CASE-SCOPED ASSISTANT</div><h2>Ask CaseWise</h2><p className="muted">Answers use only indexed documents in this case.</p><form className="ask-form" onSubmit={ask}><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="What evidence supports this claim?" minLength="3" required /><button className="primary" disabled={busy}>{busy ? 'Reviewing sources…' : 'Ask'}</button></form>{answer && <div className="answer"><div className="eyebrow">ANSWER</div><p>{answer.answer}</p><div className="eyebrow">SOURCE CITATIONS</div>{answer.citations?.length ? answer.citations.map(c => <button className="citation" key={c.chunkId} onClick={() => openDocument(c.documentId)}>{c.documentName}{c.pageNumber ? ` · Page ${c.pageNumber}` : ''} ↗</button>) : <p className="muted">No verified sources available.</p>}</div>}<p className="disclaimer">{disclaimer}</p></section>}
    {tab === 'AI Analysis' && <section className="panel"><div className="panel-head"><div><div className="eyebrow">SOURCE-VERIFIED SUGGESTIONS</div><h2>AI case review</h2></div><button className="primary" onClick={analyze} disabled={busy}>{busy ? 'Analyzing…' : 'Analyze processed documents'}</button></div><p className="muted">Suggestions require exact quotes from processed documents. Empty sections mean there was not enough verified source text.</p>{analyses.length ? <div className="analysis-grid">{Object.entries(analyses[0].result || {}).filter(([key, value]) => Array.isArray(value)).map(([key, values]) => <div className="record" key={key}><h3>{key.replace(/([A-Z])/g, ' $1')}</h3>{values.length ? values.map((v, i) => <div className="analysis-item" key={i}><p>{v.text}</p><blockquote>“{v.quote}”</blockquote><button className="link-button" onClick={() => openDocument(v.documentId)}>{v.documentName}{v.pageNumber ? ` · Page ${v.pageNumber}` : ''} ↗</button></div>) : <p className="muted">No sourced suggestions.</p>}</div>)}</div> : <div className="empty">No analysis yet. Process a document, then run a case review.</div>}<p className="disclaimer">{disclaimer}</p></section>}
    {map[tab] && <section className="panel"><div className="panel-head"><div><div className="eyebrow">CASE RECORD</div><h2>{tab}</h2></div></div>{records.length ? <div className="records">{records.map(r => <div className="record" key={r.id}><strong>{r.statement || r.name || r.title || r.description || r.purpose || r.body || r.kind || (r.total_fee !== undefined ? `Fee: ${r.total_fee} ${r.currency}` : 'Entry')}</strong><p>{r.description && r.name ? r.description : r.event_date || r.starts_at || r.due_at || r.status || ''}</p>{r.visibility && <span className="small">{r.visibility === 'CLIENT_SHARED' ? 'Shared with client' : 'Lawyer only'}</span>}</div>)}</div> : <div className="empty">No {tab.toLowerCase()} recorded yet.</div>}{lawyer && <form onSubmit={add} className="add-form"><h3>Add {tab === 'Notes' ? 'note' : tab.slice(0, -1).toLowerCase()}</h3><div className="form-grid">{fields[tab].map(([name, type]) => <label key={name}>{name.replaceAll('_', ' ')}<input type={type} step={type === 'number' ? '0.01' : undefined} value={draft[name] || ''} onChange={e => setDraft({ ...draft, [name]: e.target.value })} required={name === fields[tab][0][0]} /></label>)}<label>Visibility<select value={draft.visibility || 'LAWYER_ONLY'} onChange={e => setDraft({ ...draft, visibility: e.target.value })}><option value="LAWYER_ONLY">Lawyer only</option><option value="CLIENT_SHARED">Shared with client</option></select></label></div><button className="primary" disabled={busy}>Save entry</button></form>}</section>}
  </Shell>
}
